export type RequestDraft={property:'tower'|'villa'|'townhouse';resident:string;phone:string;building:string;unit:string;date:string;start:string;end:string;mover:string;vehicle:string;notes:string};
export function orderTotals(prices:number[],pickups:number,assemblyCount:number){
 if(!Number.isInteger(pickups)||pickups<1||pickups>prices.length)throw new Error('Pickup points must be between 1 and the number of items.');
 if(!Number.isInteger(assemblyCount)||assemblyCount<0||assemblyCount>prices.length)throw new Error('Select assembly only for items in this order.');
 if(prices.some(p=>!Number.isFinite(p)||p<0))throw new Error('Invalid furniture price.');
 const furniture=Math.round(prices.reduce((sum,p)=>sum+p,0)*100)/100,delivery=250+50*pickups,assembly=90*assemblyCount;
 return {furniture,delivery,assembly,total:furniture+delivery+assembly,trucks:1};
}
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function requestHtml(draft:RequestDraft,pickups:number,assembly:number){
 const tower=draft.property==='tower',title=tower?'Service-lift booking request':'Community gate permit request';
 const field=(label:string,value:string)=>`<div class="field"><strong>${label}</strong><div contenteditable="true" role="textbox" aria-label="${label}">${escape(value||'To be confirmed')}</div></div>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — DonkeyFlow</title><style>body{font:16px/1.6 Arial,sans-serif;color:#193d39;max-width:760px;margin:32px auto;padding:24px}h1{font-size:28px}h2{font-size:20px}.badge{color:#426d38}.field{margin:14px 0;break-inside:avoid}.field strong{display:block;font-size:14px}[contenteditable]{white-space:pre-wrap;overflow-wrap:anywhere;border-bottom:1px solid #ccd9d2;min-height:26px;padding:6px 0}button{padding:12px 20px;font:inherit;cursor:pointer;background:#237e70;color:white;border:0;border-radius:6px}.help{background:#eef5ee;padding:16px}@page{size:A4;margin:18mm}@media print{body{margin:0;padding:0;max-width:none}.help,button{display:none}[contenteditable]{border:0}h1{font-size:24px}}</style></head><body><div class="help">Edit any underlined field before printing or saving as PDF. This is a draft request; approval must come from the building or community management. <button onclick="window.print()">Print / Save PDF</button></div><p class="badge">DONKEYFLOW · MOVE-IN REQUEST DRAFT</p><h1>${title}</h1><p>Dear ${tower?'Building':'Community'} Management,</p><p>Please ${tower?'reserve the service lift and loading access':'issue a gate access permit'} for a furniture move-in at the address below.</p>${field('Property type',draft.property==='tower'?'Tower / apartment':draft.property==='villa'?'Villa':'Townhouse')}${field('Resident name',draft.resident)}${field('Contact phone',draft.phone)}${field('Building / community',draft.building)}${field('Apartment / villa / townhouse number',draft.unit)}${field('Requested date',draft.date)}${field('Requested time window',[draft.start,draft.end].filter(Boolean).join(' – '))}${field('Moving company / driver',draft.mover)}${field('Vehicle plate',draft.vehicle)}${field('Delivery details',`One truck · ${pickups} pickup point${pickups===1?'':'s'} · ${assembly} item${assembly===1?'':'s'} for assembly`)}${field(tower?'Service lift / loading instructions':'Gate / access instructions',draft.notes)}<p>Please confirm availability, required documents and any applicable access conditions.</p>${field('Resident signature','')}<p class="badge">Draft only — no booking, permit or payment has been made.</p></body></html>`;
}
