import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,Package,Layers,Leaf,Upload,Film,FileImage,Check,ChevronLeft,MapPin,Palette,Image as ImageIcon,Sofa,RefreshCw,CheckCircle2} from 'lucide-react';
import './styles.css';
import {FloorPlan,PlanPicker,RoomEditor} from './PlanEditor';
import type {PlanResult as Plan} from '../../shared/plan';
type Style={tags:string[];palette:string[];summary:string;avoid:string[]};
type Item={id:string;title:string;category:string;price_aed:number;retail_aed:number;area:string};
type Bundle={id:string;items:Item[];total_aed:number;retail_aed:number;saving_pct:number;co2_kg:number;explanation:string;warnings:string[];omitted:{category:string;reason:string}[]};
type Detected={id:string;title:string;category:string;suggested_price_aed:number;include:boolean};
const furnishSteps=['Plan & brief','Rooms','What you need','Bundle','Order'];
const sellSteps=['Upload','What we found','Your lot'];
const money=(n:number)=>new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED',maximumFractionDigits:0}).format(n);
async function api<T>(path:string,body?:object|FormData):Promise<T>{
 const form=body instanceof FormData;
 const response=await fetch(path,body?{method:'POST',headers:form?undefined:{'Content-Type':'application/json'},body:form?body:JSON.stringify(body)}:undefined);
 const result=await response.json();
 if(!response.ok)throw new Error(result.detail||'Could not load the demo. Please try again.');
 return result;
}
function App(){
 const [mode,setMode]=useState<'furnish'|'sell'|null>(null),[step,setStep]=useState(0),[tab,setTab]=useState<'Plan'|'Moodboard'|'Render'>('Plan');
 const [plan,setPlan]=useState<Plan|null>(null),[style,setStyle]=useState<Style|null>(null),[bundle,setBundle]=useState<Bundle|null>(null),[items,setItems]=useState<Detected[]>([]);
 const [brief,setBrief]=useState('A calm, comfortable home. Natural wood, soft fabrics, and a little colour.'),[needs,setNeeds]=useState(['sofa','bed','desk']);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[health,setHealth]=useState(false),[render,setRender]=useState<string|null>(null),[budget,setBudget]=useState(3000),[lotReady,setLotReady]=useState(false);
 const [building,setBuilding]=useState(''),[date,setDate]=useState('');
 const steps=mode==='sell'?sellSteps:furnishSteps;
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action()}catch(e){setError(e instanceof Error?e.message:'Something went wrong.')}finally{setBusy(false)}}
 useEffect(()=>{api<{status:string}>('/api/health').then(h=>setHealth(h.status==='ok')).catch(()=>setHealth(false))},[]);
 function choose(value:'furnish'|'sell'){setMode(value);setStep(0);setMessage('');setError('');setLotReady(false);window.scrollTo({top:0,behavior:'instant'})}
 async function analyse(body:object|FormData){await run(async()=>{const result=await api<Plan>('/api/plan',body);setPlan(result);setStep(1);setTab('Plan');setMessage(`Plan analysed with ${result.model}${result.cached?' · saved result':''}. Review dimensions before continuing.`)})}
 async function upload(file:File,kind:'plan'|'sell'){await run(async()=>{const data=new FormData();data.append('file',file);if(kind==='sell'){setItems((await api<{items:Detected[]}>('/api/sell/detect',data)).items);setStep(1)}else setPlan(await api<Plan>('/api/plan',data));setMessage('Sample data loaded. Your upload is not analysed or saved in P1.')})}
 function uploadButton(label:string,accept:string,kind:'plan'|'sell',Icon:typeof Upload){return <label className="upload-button"><Icon size={18}/><span>{label}</span><input type="file" accept={accept} disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,kind);e.target.value=''}}/></label>}
 async function loadBundle(){await run(async()=>{setBundle(await api<Bundle>('/api/bundle',{rooms:plan?.rooms,needed_categories:needs,budget_aed:budget,style,pins:{}}));setStep(3);setTab('Plan')})}
 async function next(){if(mode==='furnish'&&step===2){await loadBundle();return}setStep(Math.min(step+1,steps.length-1))}
 const total=items.filter(i=>i.include).reduce((sum,i)=>sum+i.suggested_price_aed,0);
 return <div className="app">
  <header className="header"><button className="brand" onClick={()=>{setMode(null);setError('')}} aria-label="DonkeyFlow home"><span className="brand-mark"><Layers size={22}/></span>donkey<span>flow</span><span className="period">.</span></button><div className="header-meta"><span className="place"><MapPin size={14}/>Abu Dhabi</span><span className="demo-badge">P1 / DEMO</span></div></header>
  {!mode?<main className="landing">
   <div className="landing-title"><p className="eyebrow">A NEW HOME FOR GOOD FURNITURE</p><h1>Your next move,<br/><span>a little lighter.</span></h1><p>Moving in or moving on? Let’s start with your home.</p></div>
   <div className="choice-grid">
    <button className="choice furnish-choice" onClick={()=>choose('furnish')}><div className="choice-image"><img src="/room.jpeg" alt="Bright contemporary living room with a blue sofa and natural wood flooring"/></div><div className="choice-body"><span className="choice-icon"><Home size={24}/></span><p className="eyebrow">MOVING IN</p><h2>Furnish my home</h2><p>Your space. Your style. Furniture with a second story.</p><span className="choice-cta">Start with your space <PlusSign/></span></div></button>
    <button className="choice sell-choice" onClick={()=>choose('sell')}><div className="choice-image"><img src="/room.jpeg" alt="Comfortable furniture ready for a new chapter"/></div><div className="choice-body"><span className="choice-icon"><Package size={24}/></span><p className="eyebrow">MOVING ON</p><h2>Sell everything<br className="desktop-break"/> from my home</h2><p>One walkthrough. One lot. A simpler goodbye.</p><span className="choice-cta">Start with your furniture <PlusSign/></span></div></button>
   </div>
   <div className="landing-foot"><span><Leaf size={17}/>Good pieces deserve another home.</span><span>Explore with sample data · No transactions in P1</span></div>
  </main>:<main className="workspace-page">
   <div className="workspace-heading"><div><button className="home-link" onClick={()=>setMode(null)}><ChevronLeft size={15}/>Choose your move</button><h1>{mode==='furnish'?'Make room for your new life.':'A next chapter for your furniture.'}</h1></div><div className="mode-switch" role="group" aria-label="Choose flow"><button aria-pressed={mode==='furnish'} onClick={()=>choose('furnish')}><Home size={16}/>Furnish my home</button><button aria-pressed={mode==='sell'} onClick={()=>choose('sell')}><Package size={16}/>Sell everything</button></div></div>
   <nav className="stepbar" aria-label="Progress">{steps.map((name,i)=><button key={name} onClick={()=>{setStep(i);setMessage('');setError('')}} className={i===step?'active':i<step?'complete':''} aria-current={i===step?'step':undefined}><span className="step-number">{i<step?<Check size={14}/>:String(i+1).padStart(2,'0')}</span>{name}</button>)}</nav>
   <div className="workspace">
    <section className="canvas-panel" aria-label="Visual preview">
     <div className="canvas-toolbar"><div className="tabs" role="tablist" aria-label="Canvas view">{(['Plan','Moodboard','Render'] as const).map((name,i)=><button key={name} id={'tab-'+name} role="tab" aria-selected={tab===name} aria-controls="canvas-content" tabIndex={tab===name?0:-1} onClick={()=>setTab(name)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(i+(e.key==='ArrowRight'?1:2))%3;const name=(['Plan','Moodboard','Render'] as const)[next];setTab(name);document.getElementById('tab-'+name)?.focus()}}}>{name==='Plan'?<Home size={15}/>:name==='Moodboard'?<Palette size={15}/>:<ImageIcon size={15}/>} {name}</button>)}</div><span className="canvas-tag">{plan ? "METRES" : "PLAN"}</span></div>
     <div className={'canvas-body '+(tab==='Moodboard'?'moodboard':'')} role="tabpanel" id="canvas-content" aria-labelledby={'tab-'+tab}>
      {tab==='Plan'&&(mode==='furnish'?(plan?<FloorPlan plan={plan}/>:<div className="empty"><Home size={42}/><h3>{busy?'Analysing floor plan…':'Choose or upload a floor plan'}</h3></div>):<div className="sell-overview"><Package size={54} strokeWidth={1.3}/><p className="eyebrow">ONE HOME. ONE LOT.</p><h2>Less moving.<br/>More moving on.</h2><p>Bring your pieces together<br/>for their next home.</p>{items.length>0&&<div className="sell-stats"><span><strong>{items.length}</strong>sample pieces</span><span><strong>{money(total)}</strong>sample value</span></div>}</div>)}
      {tab==='Moodboard'&&<div className="moodboard-content"><img src="/room.jpeg" alt="Living room inspiration with natural wood and blue upholstery"/><div className="palette-row">{(style?.palette??['#e3ddd0','#23877d','#8ca6a3']).map(colour=><div key={colour}><span style={{background:colour}}/><small>{colour.toUpperCase()}</small></div>)}</div><h3>{style?'Your sample style':'A calm place to begin'}</h3><p>{style?.summary??'Natural textures, simple shapes and a little colour.'}</p><span className="photo-credit">Photo: Curtis Adams / Pexels</span></div>}
      {tab==='Render'&&<div className="empty">{render?<img className="render-image" src={render} alt="DonkeyFlow demo render placeholder. Room rendering arrives in P5."/>:<><ImageIcon size={42}/><h3>Your room, reimagined.</h3><p>Room rendering arrives in P5.<br/>For now, explore the placeholder.</p></>}<button className="secondary" disabled={busy} onClick={()=>void run(async()=>setRender((await api<{image_url:string}>('/api/render',{bundle_id:bundle?.id??'demo-bundle'})).image_url))}>Load render placeholder</button></div>}
     </div>
     <div className="plan-caption"><div><strong>{tab==='Moodboard'?'Materials & colour':tab==='Render'?'Room preview':mode==='furnish'?plan?.property_kind??'Your space':'Your move-out overview'}</strong><span>{tab==='Plan'&&mode==='furnish'?`${plan?.total_area_sqm??'—'} m² · ${plan?.model??'Select a plan'}`:'Sample preview · not AI generated'}</span></div>{tab==='Plan'&&mode==='furnish'&&<span className="scale">METRES</span>}</div>
     <div className="canvas-footer"><Leaf size={15}/>A second home for furniture. A lighter footprint.</div>
    </section>
    <section className="control-panel" aria-label={steps[step]}>
     <div className="panel-heading"><p className="eyebrow">STEP {String(step+1).padStart(2,'0')} / {String(steps.length).padStart(2,'0')}</p><h2>{steps[step]}</h2><p>{mode==='furnish'?['Start with your space. We’ll help fill it.','Get to know each room.','Choose the essentials for your new home.','A first look at your furniture bundle.','Everything together, in one delivery.'][step]:['A short walkthrough is a good start.','A sample of your home’s furniture.','Bring your pieces together in one lot.'][step]}</p></div>
     <div className="controls">
      {mode==='furnish'&&step===0&&<><PlanPicker busy={busy} onAnalyse={analyse}/><label className="field">What feels like home?<textarea rows={3} value={brief} onChange={e=>setBrief(e.target.value)}/></label><button className="text-button" disabled={busy} onClick={()=>void run(async()=>{setStyle((await api<{style:Style}>('/api/intent',{text:brief})).style);setTab('Moodboard');setMessage('Sample style loaded. Your brief is not analysed in P1.')})}><Palette size={15}/>Preview style</button>{style&&<div className="style-tags">{style.tags.map(t=><span key={t}>{t}</span>)}</div>}<Notice>Upload each floor separately or crop both floors from one image. Missing dimensions need your input.</Notice></>}
      {mode==='furnish'&&step===1&&<>{plan&&<RoomEditor plan={plan} onChange={setPlan}/>}</>}
      {mode==='furnish'&&step===2&&<><div className="check-list">{[['sofa','Living room','Sofa'],['tv_unit','Living room','TV unit'],['coffee_table','Living room','Coffee table'],['armchair','Living room','Armchair'],['dining_set','Dining room','Dining set'],['bed','Bedroom','Bed frame'],['wardrobe','Bedroom','Wardrobe'],['nightstands','Bedroom','Nightstands'],['desk','Study','Desk'],['rug','Living room','Rug'],['floor_lamp','Living room','Floor lamp']].map(([id,room,title])=><label key={id}><input type="checkbox" checked={needs.includes(id)} onChange={()=>setNeeds(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id])}/><span><small>{room}</small><strong>{title}</strong></span><Sofa size={18}/></label>)}</div><label className="field budget">Furniture budget <span>{money(budget)}</span><input type="range" min={1000} max={10000} step={250} value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><Notice>Pieces are matched to your room sizes and budget. Categories with no fitting listing will be left out.</Notice></>}
      {mode==='furnish'&&step===3&&<>{bundle?<><div className="metrics"><div><span>Bundle price</span><strong>{money(bundle.total_aed)}</strong></div><div><span>Compared with new</span><strong>{money(bundle.retail_aed)}</strong></div></div><div className="bundle-items">{bundle.items.map(item=><div key={item.id}><span className="room-icon"><Sofa size={20}/></span><span><strong>{item.title}</strong><small>{item.area}</small></span><strong>{money(item.price_aed)}</strong></div>)}</div><p className="explanation">{bundle.explanation}</p>{bundle.omitted.length>0&&<p>Left out: {bundle.omitted.map(o=>`${o.category.replaceAll('_',' ')} (${o.reason})`).join('; ')}.</p>}{bundle.warnings.map(w=><Notice key={w}>{w}</Notice>)}<Notice>No items are reserved. Confirm listing availability and measurements before purchase.</Notice></>:<div className="empty small"><Sofa size={38}/><p>Build a bundle for your rooms.</p><button className="secondary" disabled={busy} onClick={()=>void loadBundle()}>Build bundle</button></div>}</>}
      {mode==='furnish'&&step===4&&<><div className="order-intro"><Package size={25}/><h3>One delivery. A fresh start.</h3><p>Delivery booking and building permits arrive in P6.</p></div><label className="field">Building or community<input value={building} onChange={e=>setBuilding(e.target.value)} placeholder="Your building name"/></label><label className="field">Preferred delivery date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="secondary" onClick={()=>setMessage('Order preview noted on this page. No booking or payment has been made.')}>Preview order</button><Notice>No order is placed in P1. Your entries are temporary and are not saved.</Notice></>}
      {mode==='sell'&&step===0&&<>{uploadButton('Upload video or photos','video/*,image/*','sell',Upload)}<div className="video-tips"><Film size={28}/><h3>A quick room-by-room walkthrough</h3><p>Keep the camera steady and show each piece clearly.</p></div><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{setItems((await api<{items:Detected[]}>('/api/sell/detect',{})).items);setStep(1)})}>Try with sample furniture</button><Notice>Your upload is not analysed or saved in this version.</Notice></>}
      {mode==='sell'&&step===1&&<>{items.length?<><div className="bundle-items">{items.map(item=><div key={item.id}><span className="room-icon"><Package size={19}/></span><span><strong>{item.title}</strong><small>Sample piece</small></span><strong>{money(item.suggested_price_aed)}</strong></div>)}</div><div className="total-row"><span>Sample lot value</span><strong>{money(total)}</strong></div><Notice>Live detection and editable prices arrive in P5.</Notice></>:<div className="empty small"><Package size={38}/><p>Try sample furniture in the Upload step.</p><button className="secondary" onClick={()=>setStep(0)}>Go to upload</button></div>}</>}
      {mode==='sell'&&step===2&&<><div className="lot-card"><Package size={28}/><h3>One move-out lot</h3><p>Keep your pieces together.</p><strong>{money(total)}</strong><small>Sample value · {items.length} pieces</small></div><button className="secondary" disabled={!items.length} onClick={()=>setLotReady(true)}>Preview your lot</button>{lotReady&&<div className="result"><CheckCircle2 size={22}/><span><strong>Sample lot ready</strong><p>Not published. No cash offer has been made.</p></span></div>}<Notice>Lot publishing arrives in P5.</Notice></>}
      {message&&<div className="feedback" role="status">{message}</div>}
      {error&&<div className="error" role="alert">{error}</div>}
     </div>
     <div className="panel-footer"><span>{busy?'Processing…':health?'API connected':'API unavailable'}</span><div>{step>0&&<button className="back" disabled={busy} onClick={()=>setStep(step-1)}>Back</button>}{step<steps.length-1&&<button className="primary" disabled={busy||(mode==='furnish'&&!plan)} onClick={()=>void next()}>Continue</button>}</div></div>
    </section>
   </div>
   <footer className="footer"><span>DonkeyFlow · Made for your next move.</span><span>Vision plan analysis · Review sizes before furnishing.</span></footer>
  </main>}
 </div>;
}
function Notice({children}:{children:React.ReactNode}){return <div className="notice"><Leaf size={17}/><span>{children}</span></div>}
function PlusSign(){return <span className="choice-plus" aria-hidden="true">+</span>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
