import React,{useState} from 'react';
import {money,type Bundle} from './BundleEditor';
import {orderTotals,requestHtml,type RequestDraft} from '../../shared/order';
export function OrderEditor({bundle,propertyKind}:{bundle:Bundle;propertyKind:string}){
 const [pickups,setPickups]=useState(Math.max(1,bundle.items.length)),[assemblyIds,setAssemblyIds]=useState<string[]>([]),[error,setError]=useState('');
 const [draft,setDraft]=useState<RequestDraft>({property:/townhouse/i.test(propertyKind)?'townhouse':/villa/i.test(propertyKind)?'villa':'tower',resident:'',phone:'',building:'',unit:'',date:'',start:'09:00',end:'12:00',mover:'',vehicle:'',notes:''});
 const assembly=bundle.items.filter(i=>assemblyIds.includes(i.id)).length;
 const totals=orderTotals(bundle.items.map(i=>i.price_aed),pickups,assembly);
 function edit<K extends keyof RequestDraft>(key:K,value:RequestDraft[K]){setDraft(old=>({...old,[key]:value}));setError('')}
 function documentAction(download:boolean){
  if(!draft.resident.trim()||!draft.building.trim()||!draft.unit.trim()||!draft.date){setError('Enter your name, building or community, unit number and delivery date before creating the request.');return}
  if(!draft.start||!draft.end||draft.end<=draft.start){setError('Choose an end time after the start time.');return}
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  if(draft.date<today){setError('Choose today or a future delivery date.');return}
  const html=requestHtml(draft,pickups,assembly);
  if(download){const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='donkeyflow-move-in-request.html';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),60000)}
  else{const page=window.open('','_blank');if(!page){setError('The printable page was blocked. Allow pop-ups or download the HTML request.');return}page.opener=null;page.document.open();page.document.write(html);page.document.close()}
 }
 const field=(key:Exclude<keyof RequestDraft,'property'|'notes'>,label:string,type='text')=><label className="field" key={key}>{label}<input type={type} value={draft[key]} onChange={e=>edit(key,e.target.value)} min={type==='date'?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()):undefined}/></label>;
 return <div className="order-editor"><div className="order-intro"><h3>One truck. One delivery.</h3><p>{bundle.items.length} furniture items · confirm pickup addresses with sellers.</p></div><label className="field">Number of pickup points<select value={pickups} onChange={e=>setPickups(Number(e.target.value))}>{bundle.items.map((_,i)=><option key={i+1} value={i+1}>{i+1} pickup point{i?'s':''}</option>)}</select><small>Starts at one pickup per listing. Combine sellers at the same address.</small></label><fieldset className="assembly-list"><legend>Which items need assembly?</legend>{bundle.items.map(item=><label key={item.id}><input type="checkbox" checked={assemblyIds.includes(item.id)} onChange={e=>setAssemblyIds(old=>e.target.checked?[...old,item.id]:old.filter(id=>id!==item.id))}/><span>{item.title}</span><strong>{money(90)}</strong></label>)}</fieldset><dl className="order-totals" aria-live="polite"><div><dt>Furniture</dt><dd>{money(totals.furniture)}</dd></div><div><dt>Delivery · 1 truck<br/><small>AED 250 + {pickups} × AED 50</small></dt><dd>{money(totals.delivery)}</dd></div><div><dt>Assembly · {assembly} items<br/><small>{assembly} × AED 90</small></dt><dd>{money(totals.assembly)}</dd></div><div className="grand-total"><dt>Total</dt><dd>{money(totals.total)}</dd></div></dl><h3 className="service-heading">Move-in request draft</h3><p className="draft-help">Prepare a request for management. Review and submit it yourself for approval.</p><label className="field">Property type<select value={draft.property} onChange={e=>edit('property',e.target.value as RequestDraft['property'])}><option value="tower">Tower / apartment · service lift</option><option value="villa">Villa · community gate permit</option><option value="townhouse">Townhouse · community gate permit</option></select></label>{field('resident','Resident name')}{field('phone','Contact phone','tel')}{field('building',draft.property==='tower'?'Building name':'Community name')}{field('unit',draft.property==='tower'?'Apartment number':'Villa / townhouse number')}{field('date','Preferred delivery date','date')}<div className="time-fields">{field('start','From','time')}{field('end','Until','time')}</div>{field('mover','Moving company / driver')}{field('vehicle','Vehicle plate (if known)')}<label className="field">{draft.property==='tower'?'Service lift / loading instructions':'Gate / access instructions'}<textarea rows={3} value={draft.notes} onChange={e=>edit('notes',e.target.value)}/></label><div className="draft-actions"><button className="primary" onClick={()=>documentAction(false)}>Open printable request</button><button className="secondary" onClick={()=>documentAction(true)}>Download HTML</button></div>{error&&<p className="error" role="alert">{error}</p>}<p className="notice">Quote and draft only. No order, payment, lift booking or gate permit has been confirmed. Keep a downloaded copy of your request.</p></div>;
}
